/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.deleghe.delegheboweb.business.aura.sanitaria;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-11-11T14:11:23.625+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "AnagrafeSanitaria", 
                  wsdlLocation = "file:/C:/Users/xyz/AppData/Local/Temp/tempdir7382294158163809623.tmp/AURA.WS.AnagrafeSanitaria_1.wsdl",
                  targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it") 
public class AnagrafeSanitaria extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", "AnagrafeSanitaria");
    public final static QName AnagrafeSanitariaSoap = new QName("http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", "AnagrafeSanitariaSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/xyz/AppData/Local/Temp/tempdir7382294158163809623.tmp/AURA.WS.AnagrafeSanitaria_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AnagrafeSanitaria.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/xyz/AppData/Local/Temp/tempdir7382294158163809623.tmp/AURA.WS.AnagrafeSanitaria_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AnagrafeSanitaria(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AnagrafeSanitaria(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnagrafeSanitaria() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AnagrafeSanitaria(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AnagrafeSanitaria(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AnagrafeSanitaria(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AnagrafeSanitariaSoap
     */
    @WebEndpoint(name = "AnagrafeSanitariaSoap")
    public AnagrafeSanitariaSoap getAnagrafeSanitariaSoap() {
        return super.getPort(AnagrafeSanitariaSoap, AnagrafeSanitariaSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnagrafeSanitariaSoap
     */
    @WebEndpoint(name = "AnagrafeSanitariaSoap")
    public AnagrafeSanitariaSoap getAnagrafeSanitariaSoap(WebServiceFeature... features) {
        return super.getPort(AnagrafeSanitariaSoap, AnagrafeSanitariaSoap.class, features);
    }

}
