/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.deleghe.delegheboweb.business.aura.sanitaria;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2021-11-11T14:11:23.617+01:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", name = "AnagrafeSanitariaSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface AnagrafeSanitariaSoap {

    @WebMethod(operationName = "GetProfiloSanitario", action = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it/AURA.WS.AnagrafeSanitaria.GetProfiloSanitario")
    @RequestWrapper(localName = "GetProfiloSanitario", targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", className = "it.csi.deleghe.delegheboweb.business.aura.sanitaria.GetProfiloSanitario")
    @ResponseWrapper(localName = "GetProfiloSanitarioResponse", targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", className = "it.csi.deleghe.delegheboweb.business.aura.sanitaria.GetProfiloSanitarioResponse")
    @WebResult(name = "GetProfiloSanitarioResult", targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it")
    public it.csi.deleghe.delegheboweb.business.aura.sanitaria.SoggettoAuraMsg getProfiloSanitario(
        @WebParam(name = "AURAid", targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it")
        java.lang.String aurAid
    );
}
