/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.deleghe.delegheboweb.business.aura.find.model;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AnagrafeFind", targetNamespace = "http://AnagrafeFind.central.services.auraws.aura.csi.it", wsdlLocation = "https://portale.ruparpiemonte.it/sanitxens/AURA.WS.AnagrafeFind.cls?wsdl")
public class AnagrafeFind
    extends Service
{

    private final static URL ANAGRAFEFIND_WSDL_LOCATION;
    private final static WebServiceException ANAGRAFEFIND_EXCEPTION;
    private final static QName ANAGRAFEFIND_QNAME = new QName("http://AnagrafeFind.central.services.auraws.aura.csi.it", "AnagrafeFind");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://portale.ruparpiemonte.it/sanitxens/AURA.WS.AnagrafeFind.cls?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANAGRAFEFIND_WSDL_LOCATION = url;
        ANAGRAFEFIND_EXCEPTION = e;
    }

    public AnagrafeFind() {
        super(__getWsdlLocation(), ANAGRAFEFIND_QNAME);
    }

    public AnagrafeFind(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANAGRAFEFIND_QNAME, features);
    }

    public AnagrafeFind(URL wsdlLocation) {
        super(wsdlLocation, ANAGRAFEFIND_QNAME);
    }

    public AnagrafeFind(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANAGRAFEFIND_QNAME, features);
    }

    public AnagrafeFind(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnagrafeFind(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AnagrafeFindSoap
     */
    @WebEndpoint(name = "AnagrafeFindSoap")
    public AnagrafeFindSoap getAnagrafeFindSoap() {
        return super.getPort(new QName("http://AnagrafeFind.central.services.auraws.aura.csi.it", "AnagrafeFindSoap"), AnagrafeFindSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnagrafeFindSoap
     */
    @WebEndpoint(name = "AnagrafeFindSoap")
    public AnagrafeFindSoap getAnagrafeFindSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://AnagrafeFind.central.services.auraws.aura.csi.it", "AnagrafeFindSoap"), AnagrafeFindSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANAGRAFEFIND_EXCEPTION!= null) {
            throw ANAGRAFEFIND_EXCEPTION;
        }
        return ANAGRAFEFIND_WSDL_LOCATION;
    }

}
