/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.deleghe.deleghebe.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import it.csi.deleghe.deleghebe.ws.msg.LeggiDescrizioneDocumento;
import it.csi.deleghe.deleghebe.ws.msg.LeggiDescrizioneDocumentoResponse;
import it.csi.deleghe.deleghebe.ws.msg.LeggiInformativaConsensi;
import it.csi.deleghe.deleghebe.ws.msg.LeggiInformativaConsensiResponse;
import it.csi.deleghe.deleghebe.ws.msg.LeggiStatiDelega;
import it.csi.deleghe.deleghebe.ws.msg.LeggiStatiDelegaResponse;
import it.csi.deleghe.deleghebe.ws.msg.LeggiStatiDichiarazione;
import it.csi.deleghe.deleghebe.ws.msg.LeggiStatiDichiarazioneResponse;
import it.csi.deleghe.deleghebe.ws.msg.LeggiTipiDelega;
import it.csi.deleghe.deleghebe.ws.msg.LeggiTipiDelegaResponse;
import it.csi.deleghe.deleghebe.ws.msg.LeggiTipiDichiarazione;
import it.csi.deleghe.deleghebe.ws.msg.LeggiTipiDichiarazioneResponse;
import it.csi.deleghe.deleghebe.ws.msg.LeggiTipoDocumento;
import it.csi.deleghe.deleghebe.ws.msg.LeggiTipoDocumentoResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DelegheCodificheService", targetNamespace = "http://deleghebe.csi.it/")
public interface DelegheCodificheService {

    @WebMethod
    public @WebResult(name="leggiStatiDichiarazioneResponse")  LeggiStatiDichiarazioneResponse leggiStatiDichiarazioneService(@WebParam(name = "leggiStatiDichiarazione")  LeggiStatiDichiarazione req);

    @WebMethod
    public @WebResult(name="leggiTipiDichiarazioneResponse")  LeggiTipiDichiarazioneResponse leggiTipiDichiarazioneService(@WebParam(name = "leggiTipiDichiarazione")  LeggiTipiDichiarazione req);

    @WebMethod
    public @WebResult(name="leggiStatiDelegaResponse")  LeggiStatiDelegaResponse leggiStatiDelegaService(@WebParam(name = "leggiStatiDelega")  LeggiStatiDelega req);
    
    @WebMethod
    public @WebResult(name="leggiTipiDelegaResponse")  LeggiTipiDelegaResponse leggiTipiDelegaService(@WebParam(name = "leggiTipiDelega")  LeggiTipiDelega req);

    @WebMethod
    public @WebResult(name="leggiTipoDocumentoResponse")  LeggiTipoDocumentoResponse leggiTipoDocumentoService(@WebParam(name = "leggiTipoDocumento")  LeggiTipoDocumento req);
    
    @WebMethod
    public @WebResult(name="leggiDescrizioneDocumentoResponse")  LeggiDescrizioneDocumentoResponse leggiDescrizioneDocumentoService(@WebParam(name = "leggiDescrizioneDocumento")  LeggiDescrizioneDocumento req);
    
    @WebMethod
    public @WebResult(name="leggiInformativaConsensiResponse")  LeggiInformativaConsensiResponse leggiInformativaConsensoService(@WebParam(name = "leggiInformativaDocumento")  LeggiInformativaConsensi req);

}
