/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.deleghe.deleghebe.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import it.csi.deleghe.deleghebe.ws.msg.AggiornaCittadino;
import it.csi.deleghe.deleghebe.ws.msg.AggiornaCittadinoResponse;
import it.csi.deleghe.deleghebe.ws.msg.AggiornaDelega;
import it.csi.deleghe.deleghebe.ws.msg.AggiornaDelegaResponse;
import it.csi.deleghe.deleghebe.ws.msg.AggiornaDichiarazione;
import it.csi.deleghe.deleghebe.ws.msg.AggiornaDichiarazioneResponse;
import it.csi.deleghe.deleghebe.ws.msg.ElencoGenitori;
import it.csi.deleghe.deleghebe.ws.msg.ElencoGenitoriResponse;
import it.csi.deleghe.deleghebe.ws.msg.GetDeleganti;
import it.csi.deleghe.deleghebe.ws.msg.GetDelegantiResponse;
import it.csi.deleghe.deleghebe.ws.msg.GetDelegati;
import it.csi.deleghe.deleghebe.ws.msg.GetDelegatiFSE;
import it.csi.deleghe.deleghebe.ws.msg.GetDelegatiFSEResponse;
import it.csi.deleghe.deleghebe.ws.msg.GetDelegatiResponse;
import it.csi.deleghe.deleghebe.ws.msg.InserisciCittadino;
import it.csi.deleghe.deleghebe.ws.msg.InserisciCittadinoResponse;
import it.csi.deleghe.deleghebe.ws.msg.InserisciDelega;
import it.csi.deleghe.deleghebe.ws.msg.InserisciDelegaResponse;
import it.csi.deleghe.deleghebe.ws.msg.InserisciDichiarazione;
import it.csi.deleghe.deleghebe.ws.msg.InserisciDichiarazioneResponse;
import it.csi.deleghe.deleghebe.ws.msg.IsAlive;
import it.csi.deleghe.deleghebe.ws.msg.IsAliveResponse;
import it.csi.deleghe.deleghebe.ws.msg.RicercaCfOperatore;
import it.csi.deleghe.deleghebe.ws.msg.RicercaCfOperatoreResponse;
import it.csi.deleghe.deleghebe.ws.msg.RicercaCittadini;
import it.csi.deleghe.deleghebe.ws.msg.RicercaCittadiniResponse;
import it.csi.deleghe.deleghebe.ws.msg.RicercaDeleghe;
import it.csi.deleghe.deleghebe.ws.msg.RicercaDelegheResponse;
import it.csi.deleghe.deleghebe.ws.msg.RicercaDichiarazioni;
import it.csi.deleghe.deleghebe.ws.msg.RicercaDichiarazioniResponse;
import it.csi.deleghe.deleghebe.ws.msg.RicercaFile;
import it.csi.deleghe.deleghebe.ws.msg.RicercaFileResponse;
import it.csi.deleghe.deleghebe.ws.msg.RinunciaDelegato;
import it.csi.deleghe.deleghebe.ws.msg.RinunciaDelegatoResponse;
import it.csi.deleghe.deleghebe.ws.msg.SaveDelegati;
import it.csi.deleghe.deleghebe.ws.msg.SaveDelegatiResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DelegheCittadiniService", targetNamespace = "http://deleghebe.csi.it/")

public interface DelegheCittadiniService {


    /**
     * 
     * @param esito
     * @param errori
     * @param in
     * @param out
     */
    @WebMethod
    public @WebResult(name="isAliveResponse")  IsAliveResponse isAliveService(@WebParam(name = "isAlive")  IsAlive req);

    /**
     * 
     * @param esito
     * @param errori
     * @param richiedente
     * @param deleganti
     * @param cittadino
     */
    @WebMethod
    public @WebResult(name="getDelegantiResponse") GetDelegantiResponse getDelegantiService(@WebParam(name = "getDeleganti") GetDeleganti req);

    /**
     * 
     * @param esito
     * @param errori
     * @param richiedente
     * @param delegato
     * @param cittadino
     * @param delegati
     * @param codiceServizio
     */
    @WebMethod
    public @WebResult(name="getDelegatiResponse") GetDelegatiResponse getDelegatiService(@WebParam(name = "getDelegati") GetDelegati req);
    
    /**
     * 
     * @param esito
     * @param errori
     * @param richiedente
     * @param delegato
     * @param cittadino
     * @param delegati
     * @param codiceServizio
     */
    @WebMethod
    public @WebResult(name="getDelegatiFSEResponse") GetDelegatiFSEResponse getDelegatiFSEService(@WebParam(name = "getDelegatiFSE") GetDelegatiFSE req);

    /**
     * 
     * @param esito
     * @param errori
     * @param richiedente
     * @param cittadino
     * @param delegati
     */
    @WebMethod
    public @WebResult(name="saveDelegatiResponse") SaveDelegatiResponse saveDelegatiService(@WebParam(name = "saveDelegati") SaveDelegati req);

    /**
     * 
     * @param esito
     * @param errori
     * @param richiedente
     * @param cittadino
     * @param cittDelServ
     */
    @WebMethod
    public @WebResult(name="rinunciaDelegatoResponse") RinunciaDelegatoResponse rinunciaDelegatoService(@WebParam(name = "rinunciaDelegato") RinunciaDelegato req);
    
    	
    
    
    
    

    @WebMethod
    public @WebResult(name="inserisciDelegaResponse")  InserisciDelegaResponse inserisciDelegaService(@WebParam(name = "inserisciDelega")  InserisciDelega req);

    @WebMethod
    public @WebResult(name="aggiornaDelegaResponse")  AggiornaDelegaResponse aggiornaDelegaService(@WebParam(name = "aggiornaDelega")  AggiornaDelega req);
    
    @WebMethod
    public @WebResult(name="ricercaDelegheResponse")  RicercaDelegheResponse ricercaDelegheService(@WebParam(name = "ricercaDeleghe")  RicercaDeleghe req);
    
    @WebMethod
    public @WebResult(name="ricercaCfOperatoreResponse") RicercaCfOperatoreResponse ricercaCfOperatoreService(@WebParam(name = "ricercaCfOperatoreServizio") RicercaCfOperatore req);
    
    @WebMethod
    public @WebResult(name="ricercaCfOperatoreResponse") RicercaCfOperatoreResponse ricercaOperatoreValidoService(@WebParam(name = "ricercaCfOperatoreServizio") RicercaCfOperatore req);
    

    
    @WebMethod
    public @WebResult(name="inserisciDichiarazioneResponse")  InserisciDichiarazioneResponse inserisciDichiarazioneService(@WebParam(name = "inserisciDichiarazione")  InserisciDichiarazione req);

    @WebMethod
    public @WebResult(name="aggiornaDichiarazioneResponse")  AggiornaDichiarazioneResponse aggiornaDichiarazioneService(@WebParam(name = "aggiornaDichiarazione")  AggiornaDichiarazione req);
    
    @WebMethod
    public @WebResult(name="ricercaDichiarazioniResponse")  RicercaDichiarazioniResponse ricercaDichiarazioniService(@WebParam(name = "ricercaDichiarazioni")  RicercaDichiarazioni req);
    
    @WebMethod
    public @WebResult(name="elencoGenitoreResponse")  ElencoGenitoriResponse elencoGenitoriService(@WebParam(name = "elencoGenitore")  ElencoGenitori req);
    

    
    @WebMethod
    public @WebResult(name="inserisciCittadinoResponse")  InserisciCittadinoResponse inserisciCittadinoService(@WebParam(name = "inserisciCittadino")  InserisciCittadino req);

    @WebMethod
    public @WebResult(name="ricercaCittadiniResponse")  RicercaCittadiniResponse ricercaCittadiniService(@WebParam(name = "ricercaCittadino")  RicercaCittadini req);
    
    @WebMethod
    public @WebResult(name="aggiornaCittadinoResponse")  AggiornaCittadinoResponse aggiornaCittadinoService(@WebParam(name = "aggiornaCittadino")  AggiornaCittadino req);
    
    @WebMethod
    public @WebResult(name="ricercaFileDocumentoPerId")  RicercaFileResponse ricercaFileDocumentoPerId(@WebParam(name = "ricercaFile")  RicercaFile req);


}
