/**
 * Servizi trasversali
 * Api risorse per gestire i servizi trasversali
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
import {DateCrit} from './dateCrit';
import {StringCrit} from './stringCrit';


export interface ComuneFilter {
  /**
   * descrizione del comune (in like o eq)
   */
  desc?: StringCrit;
  /**
   * codice catastale del comune
   */
  codiceCatasto?: StringCrit;
  /**
   * data di validita del comune compresa tra  data_inizio_validita e data_fine_validita
   */
  dataValidita?: DateCrit;
}
