/**
 * DELEGHEBO_API
 * API del back office di Deleghe.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

export interface DeletServizioParametro {

  ser_id: number;
  validita_servizio?: string;
  codice?: string;
  /*serpar_id: number;
  serpar_code?: string;
  serpar_desc?: string;
  serpar_valore?: string;
  validita_inizio?: Date;
  validita_fine: Date;
  data_creazione?: Date;
  data_modifica: Date;
  data_cancellazione: Date;
  login_operazione?: string;
  ruoloop_id?: number;*/
}
