/**
 * DELEGHEBO_API
 * API del back office di Deleghe.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
import {Cittadino} from './cittadino';
import {DelegaServizio} from './delegaServizio';
import {DichiarazioneDettaglio} from './dichiarazioneDettaglio';


export interface Delega {
  numero_pratica?: number;
  cit_id_delegato?: number;
  cit_id_delegante?: number;
  full_compilatore_cf: any;
  uuid?: string;
  delegante?: Cittadino;
  blocca_delega?: boolean;
  delegato?: Cittadino;
  richiesta?: Date;
  motivazione_menu?: string;
  dichiarazione_dettaglio?: DichiarazioneDettaglio;
  motivazione_casella?: string;
  compilatore_cf?: string;
  tipo_delega?: string;
  stato_delega?: string;
  /**
   * gestisce cancellazione o attivazione valori possibili attivi, eliminato
   */
  stato?: string;
  servizi?: Array<DelegaServizio>;
}
