/**
 * Servizi trasversali
 * Api risorse per gestire i servizi trasversali
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
import { Regione } from './regione';


export interface Provincia {
    /**
     * codice della provincia di appartenenza
     */
    codiceIstat?: string;
    /**
     * descrizione della provincia
     */
    desc?: string;
    /**
     * sigla della provincia
     */
    sigla?: string;
    regione?: Regione;
}
