/**
 * Servizi trasversali
 * Api risorse per gestire i servizi trasversali
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
import {Nazione} from './nazione';


export interface Regione {
  /**
   * codice della regione
   */
  codiceIstat?: string;
  /**
   * descrizione della regione
   */
  desc?: string;
  nazione?: Nazione;
}
