/**
 * DELEGHEBO_API
 * API del back office di Deleghe.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Utente { 
    nome?: string;
    cognome?: string;
    codice_fiscale?: string;
    id_provider?: string;
    timestamp?: string;
    livello_autenticazione?: string;
}
